function(setup_python)
    set(PYTHON_VENV "${PROJECT_SOURCE_DIR}/.venv")

    if (NOT EXISTS "${PROJECT_SOURCE_DIR}/.venv")
        find_package (Python3 3.11 EXACT COMPONENTS Interpreter)
        message(STATUS "Creating virtual env: ${PYTHON_VENV}")
        execute_process (COMMAND "${Python3_EXECUTABLE}" -m venv "${PYTHON_VENV}")
    else ()
        message(STATUS "Re-using virtual env: ${PYTHON_VENV}")
    endif ()

    set (ENV{VIRTUAL_ENV} "${PYTHON_VENV}")
    set (Python3_FIND_VIRTUALENV ONLY)
    unset (Python3_EXECUTABLE)
    message(STATUS "Looking for Python in virtual env: ${PYTHON_VENV}")
    find_package (Python3 COMPONENTS Interpreter Development)

    if (${UPDATE_PYTHON_DEPS})
        message(STATUS "Updating dependencies in virtual env: ${PYTHON_VENV}")
        execute_process(COMMAND "${PYTHON_VENV}/bin/pip3" install -r "${PROJECT_SOURCE_DIR}/requirements.txt" --upgrade)
    endif ()
endfunction()
