function(setup_python)
    set(PYTHON_VENV "${PROJECT_SOURCE_DIR}/.venv")
    find_package (Python3 COMPONENTS Interpreter)
    message(STATUS "Creating virtual env: ${PYTHON_VENV}")
    execute_process (COMMAND "${Python3_EXECUTABLE}" -m venv "${PYTHON_VENV}")
    set (ENV{VIRTUAL_ENV} "${PYTHON_VENV}")
    set (Python3_FIND_VIRTUALENV FIRST)
    unset (Python3_EXECUTABLE)
    message(STATUS "Looking for Python in virtual env: ${PYTHON_VENV}")
    find_package (Python3 COMPONENTS Interpreter Development)
    message(STATUS "Updating dependencies in virtual env: ${PYTHON_VENV}")
    execute_process (COMMAND "${PYTHON_VENV}/bin/pip" install -r "${PROJECT_SOURCE_DIR}/requirements.txt" --upgrade)
endfunction()
